events {
    worker_connections 1024;
}

http {
    types {
        text/javascript          js mjs;
        text/css                 css;
        text/html                html htm;
        image/svg+xml            svg;
        image/png                png;
        image/jpeg               jpeg jpg;
        font/woff2               woff2;
    }
    
    default_type application/octet-stream;
    sendfile on;

    # 1. HTML/JS Website (Portal)
    server {
        listen 80;
        server_name semantec.lan www.semantec.lan web.semantec.lan portal.semantec.lan;
        
        location / {
            root /usr/share/nginx/portal;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
    
    # 2. React Devlab
    server {
        listen 80;
        server_name dev.semantec.lan devlab.semantec.lan;
        
        location / {
            root /usr/share/nginx/devlab;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
